# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  identifier = "文章"
  pre = "pencil"
  name = "文章"
  pageRef = "articels"
  weight = 10

[[main]]
  name = "推荐"
  pre = "lightbulb"
  pageRef = "recommend"
  weight = 20

[[main]]
  name = "标签"
  pre = "tag"
  pageRef = "tags"
  weight = 40

[[main]]
  pre = "github"
  url = "https://github.com/Weaxs"
  weight = 50


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "标签"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "推荐"
  pageRef = "recommend"
  weight = 20
  
[[footer]]
  name = "统计"
  url = "https://umami-umami.koyeb.app/share/bfDoQvG6gOqUYRbN/blog"
  weight = 30

#[[footer]]
#  name = "机核网"
#  url = "https://www.gcores.com/"
#  weight = 20
#
#[[footer]]
#  name = "智堡"
#  url = "https://wisburg.com/"
#  weight = 30
#
#[[footer]]
#  name = "新经济思维研究所"
#  url = "https://www.ineteconomics.org/"
#  weight = 40

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
