# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/configuration/#theme-parameters

colorScheme = "congo"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = false
defaultBackgroundImage = "img/elden-ring-backgroud.png"

enableSearch = true
enableCodeCopy = true

mainSections = ["articels", "recommend", "notes"]
# robots = ""

[header]
  layout = "fixed" # valid options: basic, fixed

[footer]
 # showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background" # valid options: page, profile, hero, card, background, custom
  homepageImage = "img/elden-ring-backgroud.png" # used in: hero, and card
  showRecent = true
  showRecentItems = 9
  showMoreLink = true
  showMoreLinkDest = "/articels"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = false # only used when layout equals background

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateUpdated = false
  showAuthor = true
  showHero = true
  heroStyle = "background" # valid options: basic, big, background
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showAuthorsBadges = false 
  showWordCount = true
  showSummary = true
  showComments = true
  sharingLinks = [ "email",  "twitter", "telegram"]
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = false
  showRelatedContent = true
  relatedContentLimit = 3

[list]
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showCards = false
  groupByYear = true
  cardView = false
  cardViewScreenWidth = true
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = false
  layoutBackgroundHeaderSpace = true

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground


[firebase]
  # apiKey = "XXXXXX"
  # authDomain = "XXXXXX"
  # projectId = "XXXXXX"
  # storageBucket = "XXXXXX"
  # messagingSenderId = "XXXXXX"
  # appId = "XXXXXX"
  # measurementId = "XXXXXX"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""

[umamiAnalytics]
  websiteid = "7bf15f5e-1928-4ef3-935a-e72e00d871f8"
  domain = "umami.weaxsey.org"
