version: '3'
services:
  hugo-server:
    image: hugomods/hugo:latest
    command: hugo server --bind 0.0.0.0
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
    container_name: hugo-blowfish